import React from 'react';
import { Button } from './Button';
import { MeetingAnalysis } from '../types';

interface WinModalProps {
  timeMs: number;
  onPlayAgain: () => void;
  topic: string;
  analysis: MeetingAnalysis | null;
}

export const WinModal: React.FC<WinModalProps> = ({ timeMs, onPlayAgain, topic, analysis }) => {
  const formatTime = (ms: number) => {
    const totalSeconds = Math.floor(ms / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}m ${seconds}s`;
  };

  const getShareText = () => {
    const scoreText = analysis ? `Boredom Score: ${analysis.boredomScore}% 😴` : '';
    return `I got a Bingo in ${formatTime(timeMs)} during a meeting about "${topic}"! ${scoreText} Generated by Meeting Bingo AI.`;
  };

  const shareUrl = window.location.href;
  const shareText = getShareText();

  const handleTwitterShare = () => {
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
    window.open(url, '_blank');
  };

  const handleFacebookShare = () => {
    // FB share usually takes just the URL, but we can try to rely on OG tags if we had them. 
    // For client side simple share:
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`;
    window.open(url, '_blank');
  };

  const handleCopyForInstagram = () => {
    navigator.clipboard.writeText(shareText + " " + shareUrl);
    alert('Copied! Open Instagram and paste this into your Story or Post.');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-white rounded-3xl shadow-2xl p-6 max-w-md w-full text-center transform animate-in zoom-in-95 duration-300 max-h-[90vh] overflow-y-auto">
        
        <div className="mb-6">
          <div className="text-6xl mb-2 animate-bounce">🏆</div>
          <h2 className="text-3xl font-bold text-slate-800">BINGO!</h2>
        </div>

        {/* Analysis Section */}
        <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl p-6 mb-6 border border-indigo-100">
           {!analysis ? (
             <div className="flex flex-col items-center justify-center py-4 gap-3">
               <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div>
               <p className="text-sm text-indigo-600 font-medium animate-pulse">Gemini is judging your meeting...</p>
             </div>
           ) : (
             <div className="animate-in slide-in-from-bottom-4 fade-in duration-500">
               <div className="flex justify-between items-center mb-4 pb-4 border-b border-indigo-100">
                 <div className="text-left">
                   <p className="text-xs uppercase tracking-wider text-indigo-400 font-bold">Time</p>
                   <p className="text-xl font-mono font-bold text-slate-700">{formatTime(timeMs)}</p>
                 </div>
                 <div className="text-right">
                   <p className="text-xs uppercase tracking-wider text-indigo-400 font-bold">Boredom Score</p>
                   <div className="flex items-baseline justify-end gap-1">
                     <p className={`text-3xl font-bold ${analysis.boredomScore > 75 ? 'text-red-500' : analysis.boredomScore > 40 ? 'text-yellow-600' : 'text-green-600'}`}>
                       {analysis.boredomScore}
                     </p>
                     <span className="text-sm text-slate-400">%</span>
                   </div>
                 </div>
               </div>
               <p className="text-slate-700 italic font-medium leading-relaxed">
                 "{analysis.commentary}"
               </p>
             </div>
           )}
        </div>

        <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-widest mb-3">Share Your Win</h3>
        
        <div className="grid grid-cols-3 gap-3 mb-6">
          <button 
            onClick={handleTwitterShare}
            className="flex flex-col items-center justify-center p-3 rounded-xl bg-slate-900 text-white hover:bg-slate-700 transition-colors"
          >
            <span className="text-xl mb-1">𝕏</span>
            <span className="text-xs font-medium">Post</span>
          </button>
          
          <button 
            onClick={handleFacebookShare}
            className="flex flex-col items-center justify-center p-3 rounded-xl bg-blue-600 text-white hover:bg-blue-700 transition-colors"
          >
            <span className="text-xl mb-1">f</span>
            <span className="text-xs font-medium">Share</span>
          </button>

          <button 
            onClick={handleCopyForInstagram}
            className="flex flex-col items-center justify-center p-3 rounded-xl bg-gradient-to-tr from-yellow-400 via-red-500 to-purple-600 text-white hover:opacity-90 transition-opacity"
          >
            <span className="text-xl mb-1">📷</span>
            <span className="text-xs font-medium">Insta</span>
          </button>
        </div>

        <Button onClick={onPlayAgain} variant="outline" className="w-full">
          Play Again
        </Button>
      </div>
    </div>
  );
};